### ISSUE TITLE
rescue in login': uninitialized constant VagrantPlugins::Login::Client::RestClient

### ISSUE THREAD

**Issue by philbert** [hashicorp/vagrant-plugin-changelog#2]
This appears like a client-side error, however I can't help but feel it must be vagrant cloud that's down right now? It worked a few weeks ago and I can't think of anything that has changed in my setup.

16:22 ~ → vagrant login
In a moment we'll ask for your username and password to Vagrant Cloud.
After authenticating, we will store an access token locally. Your
login details will be transmitted over a secure connection, and are
never stored on disk locally.

If you don't have a Vagrant Cloud account, sign up at vagrantcloud.com

Username or Email: asdfasfsa
Password (will be hidden):
/Applications/Vagrant/embedded/gems/gems/vagrant-login-1.0.1/lib/vagrant-login/client.rb:52:in `rescue in login': uninitialized constant VagrantPlugins::Login::Client::RestClient (NameError)
	from /Applications/Vagrant/embedded/gems/gems/vagrant-login-1.0.1/lib/vagrant-login/client.rb:46:in `login'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-login-1.0.1/lib/vagrant-login/activated.rb:52:in `execute'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:42:in `execute'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:292:in `cli'
	from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:174:in `<main>'

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening an issue, and sorry this went unnoticed. In the future, please open these issues on the Vagrant project at https://github.com/mitchellh/vagrant :smile: 

Please upgrade to the latest version of Vagrant (1.8.1) and see if this problem persists.
