### ISSUE TITLE
VMWare-Workstation changelog not current

### ISSUE THREAD

**Issue by davidski** [hashicorp/vagrant-plugin-changelog#7]
The `vagrant-vmware-workstation` plugin changelog is current only through V4.0.2. V4.0.5 version is available and needs documentation as to the changes.

**Comment by mathewpeterson** [comment]
It would be very helpful to have an updated change log.

**Comment by davidski** [comment]
Very much appreciate the updated changelog @sethvargo. :) The notes only go through V4.0.4 and V4.0.5 is released. Would you please do another update to indicate what changed in that version?
